//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIR6_26.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bis
    {
        public int id_bis { get; set; }
        public int id_member { get; set; }
        public string dari { get; set; }
        public string ke { get; set; }
        public int saldo { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
